[[constraint]]
  name = "github.com/gorhill/cronexpr"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.1.4"
